version: '3.8'
services:
  backend:
    build: ./backend
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - /backend
  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app:delegated"
      - "/app/node_modules"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080